# vim ft=yaml
# travis-ci.org definition for Nimfa tests
language: python

sudo: false

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev

python:
  - "2.7"
#  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - sudo apt-get update

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest matplotlib Pillow
  - pip install pep8 python-coveralls pytest-cov
  - pip install -e .

services:
  - xvfb

before_script:
  - wget http://files.grouplens.org/datasets/movielens/ml-100k.zip -P nimfa2/datasets/MovieLens/
  - unzip -j nimfa2/datasets/MovieLens/ml-100k.zip -d  nimfa2/datasets/MovieLens/
  - wget http://www.ai.mit.edu/courses/6.899/lectures/faces.tar.gz -P nimfa2/datasets/CBCL_faces/
  - tar zxvf nimfa2/datasets/CBCL_faces/faces.tar.gz -C nimfa2/datasets/CBCL_faces/
  - tar zxvf nimfa2/datasets/CBCL_faces/face.train.tar.gz -C nimfa2/datasets/CBCL_faces/
  - mv nimfa2/datasets/CBCL_faces/train/face/ nimfa2/datasets/CBCL_faces/

script:
  - py.test --cov=nimfa2

after_success:
  - coveralls

# TODO Later if you decide to upload tagged releases to pypi automagically
# see https://docs.travis-ci.com/user/deployment/pypi/ for details
#deploy:
#  provider: pypi
#  distributions: sdist
#  user: YOURUSERNAME
#  password:
#    secure: YOUR_ENCRYPTED_WITH_TRAVISTOOLS_PASSWORD_FOR_PYPI
#  on:
#    tags: true
#    branch: master
#    repo: YOURGITHUBLOGIN/nimfa2
#    condition: "$TRAVIS_PYTHON_VERSION == 2.7 && $TRAVIS_TAG =~ ^v[0-9]*[.][.0-9]*"
